customers/urls.py
from django.contrib import admin
from django.urls import path,include
from customers import views

urlpatterns = [
    path('show_account',views.show_account, name='show_account'),
    path('sign_out', views.sign_out, name="sign_out")
    

]

ecom_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),   
    path('',include('products.urls')),
    path('customers/', include(('customers.urls', 'customers'), namespace='customers')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib import admin
from django.urls import path,include
from orders import views

urlpatterns = [
    path('show_cart', views.show_cart,name='show_cart'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('checkout/',views.checkout,name='checkout'),
    

]

products/urls.py
from django.contrib import admin
from django.urls import path,include
from products import views

urlpatterns = [
    path('',views.index, name='index'),
    path('product_list', views.product_list, name='product_list'),
    path('product_detail/<pk>',views.product_detail,name='product_detail'),
    path('contact',views.contact,name='contact'),

]

customers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    LIVE=1
    DELETE=0
    DELETE_CHOICE=((LIVE,'Live'),(DELETE,'Delete'))
    name=models.CharField(max_length=100)
    address=models.TextField()
    user=models.OneToOneField(User, related_name='customer_profile', 
                              on_delete=models.CASCADE)
    phone=models.CharField(max_length=10)
    delete_status=models.IntegerField(choices=DELETE_CHOICE, default=LIVE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

orders/models.py
from django.db import models
from customers.models import Customer
from products.models import Products

# Create your models here.

class Order(models.Model):
    LIVE=1
    DELETE=0
    DELETE_CHOICE=((LIVE,'Live'),(DELETE,'Delete'))
    CART_STAGE=0
    ORDER_CONFIRMED=1
    ORDER_PROCESSED=2
    ORDER_DELIVERED=3
    ORDER_REJECTED=4
    STATUS_CHOICE=((ORDER_PROCESSED,'ORDER_PROCESSED'),
                   (ORDER_CONFIRMED,'ORDER_CONFIRMED'),
                   (ORDER_DELIVERED,'ORDER_DELIVERED'),
                   (ORDER_REJECTED,'ORDER_REJECTED')                   
                   )
    order_status=models.IntegerField(choices=STATUS_CHOICE, default=CART_STAGE)
    owner=models.ForeignKey(Customer,on_delete=models.SET_NULL, related_name='orders',null=True)
    delete_status=models.IntegerField(choices=DELETE_CHOICE, default=LIVE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class OrderedItem(models.Model):
    product=models.ForeignKey(Products,on_delete=models.SET_NULL, 
                              related_name='added_carts',null=True)
    quantity=models.ImageField(default=1)
    owner=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='added_items')

products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    LIVE=1
    DELETE=0
    DELETE_CHOICE=((LIVE,'Live'),(DELETE,'Delete'))

    title=models.CharField(max_length=200)
    price=models.FloatField()
    description=models.TextField()
    image=models.ImageField(upload_to='media/')
    priority=models.IntegerField(default=0)
    delete_status=models.IntegerField(choices=DELETE_CHOICE, default=LIVE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

theme/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from . models import Customer
from django.contrib import messages
from django.contrib.auth import authenticate, login,logout
# Create your views here.

def show_account(request):
    context={

    }
    if request.POST and 'register' in request.POST:
        context['register']=True
        try:
            username=request.POST.get('username')
            email=request.POST.get('email')
            password=request.POST.get('password')
            address=request.POST.get('address')
            phone=request.POST.get('phone')

            # print(request.POST) 
            # Create user Account

            user=User.objects.create_user(
                username=username,
                email=email,
                password= password
            )
            # create Customer Accont
            customer=Customer.objects.create(
                user=user,
                phone=phone,
                address=address
            )
            return redirect('#')
        except Exception as e:
            error_message="User already exsits..!"
            messages.error(request,error_message)
        


# =================login ==================
    if request.POST and 'login' in request.POST:
        context['register']=False
        username=request.POST.get('username') 
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)      
        if user:
            login(request,user)
            return redirect('index')
        else:
            # If authentication fails, display an invalid credentials message
            messages.error(request, "Invalid username or password. Please try again.")

    return render(request,'login.html',context )

# ====================== LOG OUT ======================================

def sign_out(request):
    logout(request)
    return redirect('index')

orders/views.py
from django.shortcuts import render,redirect
from . models  import *
from products.models import *

# Create your views here.
def show_cart(request):

    return render(request, 'cart.html')

def add_to_cart(request):
    if request.POST:
        user=request.user
        customer=user.customer_profile
        quantity=request.POST.get('quantity')
        product_id=request.POST.get('product_id')
        cart_obj, created =Order.objects.get_or_create(
            owner=customer,
            order_status=Order.CART_STAGE
        )
        product= Products.objects.get(pk= product_id)
        ordered_item=OrderedItem.objects.create(
            
            product=product,
            owner=cart_obj,
            quantity=quantity
        )
    
    return redirect('cart')





















def checkout(request):
    return render(request,'checkout.html')

products/views.py
from django.shortcuts import render
from . models import *
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    featured_product=Products.objects.order_by('priority')[:4]
    recent_product=Products.objects.order_by('-id')[:4]
    context={
        'featured_product':featured_product,
        'recent_product':recent_product,
    }
    return render(request,'index.html',context)

def product_list(request):
    page=1
    if request.GET:
        page=request.GET.get('page',1)
    product_data=Products.objects.all()
    product_paginator=Paginator(product_data,3)
    product_data=product_paginator.get_page(page)
    context={
        'product_data':product_data
    }
    return render(request,'products.html',context) 

def product_detail(request,pk):
    all_product=Products.objects.all()
    product=Products.objects.get(pk=pk)
    context={
        'product':product,
        'all_product':all_product,
    }
    return render(request, 'detail.html',context)

def contact(request):
    return render(request,'contact.html')

theme/views.py
from django.shortcuts import render

# Create your views here.

templates/blank_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Foot Wears</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/logo.jpg' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Foot</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Wears</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-6 text-right">
            <!-- <p class="m-0">My Account</p> -->
            <div class="btn-group">
                <!-- {% if user.is_authenticated %}

                {{user.username}}
                {% endif %} -->
                <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">
                    <a href="" style="color: black;" class="btn px-0 ml-3">
                        <i class="fas fa-user text-primary" style="display: block;"></i>
                        {% if user.is_authenticated %}
                        {{user.username}}

                        {% else %}
                        Profile
                        {% endif %}
                    </a>
                </button>
                {% if not user.is_authenticated %}
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'customers:show_account' %}"><button class="dropdown-item" type="button">Sign
                            in</button></a>
                    <a href="{% url 'customers:show_account' %}"> <button class="dropdown-item" type="button">Sign
                            up</button></a>
                    {% else %}
                    <a href="{% url 'customers:sign_out' %}"> <button class="dropdown-item" type="button">Sign
                            Out</button></a>
                </div>
                {% endif %}

            </div>

        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">

            <div class="col-lg  ">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">

                    <!-- <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button> -->
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'index' %}" class="nav-item nav-link active">Home</a>
                            <!-- <a href="{% url 'index' %}" class="nav-item nav-link ">Women</a> -->
                            <!-- <a href="{% url 'index' %}" class="nav-item nav-link ">Men</a> -->
                            <!-- <a href="{% url 'index' %}" class=" nav-item nav-link ">Kids</a> -->
                            <a href=" {% url 'product_list' %}" class="nav-item nav-link">Products</a>

                            <!-- <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i
                                        class="fa fa-angle-down mt-1"></i></a>
                                <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                    <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                    <a href="checkout.html" class="dropdown-item">Checkout</a>
                                </div>
                            </div> -->
                            <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                            <!-- <a href="" class="btn px-0">
                                <i class="fas fa-heart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle"
                                    style="padding-bottom: 2px;">0</span>
                            </a> -->
                            <a href="{% url 'orders:show_cart' %}" class="btn px-0 ml-3">
                                <i class="fas fa-shopping-cart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle"
                                    style="padding-bottom: 2px;">0</span>
                            </a>

                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->




    {% block content %}
    {% endblock %}





    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor.
                    Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>gdhdh</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+78012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">

                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>

                    <div class="col-md-4 mb-5"> </div>

                    <div class="col-md-4 mb-5">
                        <div class="col-lg-4">
                            <a href="" class="text-decoration-none">
                                <span class="h1 text-uppercase text-primary bg-dark px-2">Foot</span>
                                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Wears</span>
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <!-- <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div> -->
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/cart.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
{% if cart %}
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for cart_item in cart.added_items.all %}
                    <tr>
                        <td class="align-middle"><img src="{{ cart_item.product.image.url }}" alt=""
                                style="width: 50px;"> Product
                            Name</td>
                        <td class="align-middle">₹1{{cart_item.product.price}}</td>
                        <td class="align-middle">

                            <input type="text" disabled
                                class="form-control form-control-sm bg-secondary border-0 text-center"
                                value="{{cart_item.quantity}}">

        </div>
        </td>
        <td class="align-middle">$150</td>
        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
        </tr>
        {% endfor %}

        </tbody>
        </table>
    </div>
    <div class="col-lg-4">

        <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart
                Summary</span></h5>
        <div class="bg-light p-30 mb-5">
            <div class="border-bottom pb-2">
                <div class="d-flex justify-content-between mb-3">
                    <h6>Subtotal</h6>
                    <h6>$150</h6>
                </div>
                <div class="d-flex justify-content-between">
                    <h6 class="font-weight-medium">Shipping</h6>
                    <h6 class="font-weight-medium">$10</h6>
                </div>
            </div>
            <div class="pt-2">
                <div class="d-flex justify-content-between mt-2">
                    <h5>Total</h5>
                    <h5>$160</h5>
                </div>
                <a href="{% url 'orders:checkout' %}">
                    <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To
                        Checkout</button>
                </a>

            </div>
        </div>
    </div>
</div>
{% else %}
<h4>Empty Cart..!</h4>
{% endif %}
<!-- Cart End -->
{% endblock %}

templates/contact.html
{% extends 'blank_layout.html' %}
{% load static %}
{% block content %}


<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <span class="breadcrumb-item active">Contact</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Contact Start -->
<div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact
            Us</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                <div id="success"></div>
                <form name="sentMessage" id="contactForm" novalidate="novalidate">
                    <div class="control-group">
                        <input type="text" class="form-control" id="name" placeholder="Your Name" required="required"
                            data-validation-required-message="Please enter your name" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="email" class="form-control" id="email" placeholder="Your Email" required="required"
                            data-validation-required-message="Please enter your email" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="text" class="form-control" id="subject" placeholder="Subject" required="required"
                            data-validation-required-message="Please enter a subject" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <textarea class="form-control" rows="8" id="message" placeholder="Message" required="required"
                            data-validation-required-message="Please enter your message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                            Message</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3927.822536329!2d76.47004987037165!3d10.113607948989042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b07e28a16930f9f%3A0x75ec78eaf485f0f0!2sPerumbavoor%20Municipality%20Shopping%20Mall!5e0!3m2!1sen!2sin!4v1710347193038!5m2!1sen!2sin"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Perumbavoor</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->

{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<!-- Created by CodingLab |www.youtube.com/c/CodingLabYT-->
<html lang="en" dir="ltr">

<head>
  <meta charset="UTF-8">
  <!--<title> Login and Registration Form in HTML & CSS | CodingLab </title>-->
  <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
  <!-- Fontawesome CDN Link -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <div class="container">
    <input type="checkbox" id="flip">
    <div class="cover">
      <div class="front">
        <img src="{% static 'img/offer-1.jpg' %}" alt="">
        <div class="text">
          <span class="text-1">Wherever you go <br> I'm there</span>
          <span class="text-2">visit us</span>
        </div>
      </div>
      <div class="back">
        <!-- <img class="backImg" src="img/offer-1.jpg" alt=""> -->
        <div class="text">
          <span class="text-1">Wherever you go <br>I'm there</span>
          <span class="text-2">visit us</span>
        </div>
      </div>
    </div>

    <div class="forms">
      <div class="form-content">
        <div class="login-form">
          <div class="title">Login</div>

          <div class="log_message">
            {% if messages %}
            <p>
              {% for message in messages %}
              {{message }}
              {% endfor %}
            </p>

            {% endif %}
          </div>

          <!-- =========Login Starts============ -->
          <form action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" name="username" placeholder="Enter your Username" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" name="password" placeholder="Enter your Password" required>
              </div>

              <div class="text"><a href="#">Forgot password?</a></div>
              <div class="button input-box">
                <input type="submit" value="LogIn" name="login" onclick="validateLoginForm()">
              </div>
              <div class="text sign-up-text">Don't have an account? <label for="flip">Sigup now</label></div>
            </div>
          </form>
          <!-- =========Login ends============ -->
        </div>


        <div class="signup-form">
          <div class="title">Signup</div>
          <div class="sign_message">
            {% if register %}
            {% if messages %}
            <p>
              {% for message in messages %}
              {{message }}
              {% endfor %}
            </p>

            {% endif %}
            {% endif %}
          </div>

          <!-- =========Signup Starts============ -->
          <form action="#" method="post" enctype="multipart/form-data" n>
            {% csrf_token %}
            <div class="input-boxes">
              <div class="input-box">
                <i class="fas fa-user"></i>
                <input type="text" name="username" placeholder="Enter User name" required>
              </div>
              <div class="input-box">
                <i class="fas fa-envelope"></i>
                <input type="email" name="email" placeholder="Enter your email" required>
              </div>
              <div class="input-box">
                <i class="fas fa-lock"></i>
                <input type="password" name="password" placeholder="Enter your password" required>
              </div>
              <div class="input-box">
                <i class="fas fa-address-book"></i>
                <input type="text" name="address" placeholder="Enter your address" required>
              </div>
              <div class="input-box">
                <i class="fas fa-phone"></i>
                <input type="text" name="phone" placeholder="Enter your phone number" required>
              </div>
              <div class="button input-box">
                <input type="submit" value="Register" name="register" onclick="validateRegistrationForm()">
              </div>
              <div class="text sign-up-text">Already have an account? <label for="flip">Login now</label></div>
            </div>
          </form>
          <!-- =========Signup ends============ -->

        </div>
      </div>
    </div>
  </div>


  <script src="{% static 'js/validation.js' %}"></script>

</body>

</html>